2022-02-03 09:44:40,174 - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''sub_name' = 'biology' WHERE 'sub_name' = 'zoology'' at line 1") 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''sub_name' = 'biology' WHERE 'sub_name' = 'zoology'' at line 1")
2022-02-03 09:46:25,133 - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''sub_name' = 'biology' WHERE 'sub_name' = 'zoology'' at line 1") 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''sub_name' = 'biology' WHERE 'sub_name' = 'zoology'' at line 1")
2022-02-03 09:52:59,250 - not enough arguments for format string 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 146, in execute
    query = self.mogrify(query, args)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 125, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
2022-02-03 09:53:32,630 - not enough arguments for format string 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 146, in execute
    query = self.mogrify(query, args)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 125, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
2022-02-03 09:56:07,444 - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''teacher_first_name' = 'akshay' WHERE 'teacher_first_name' = 'rajat'' at line 1") 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''teacher_first_name' = 'akshay' WHERE 'teacher_first_name' = 'rajat'' at line 1")
2022-02-03 10:02:19,673 - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(teacher_first_name) = 'akshay' WHERE (teacher_first_name) = 'rajat'' at line 1") 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(teacher_first_name) = 'akshay' WHERE (teacher_first_name) = 'rajat'' at line 1")
2022-02-03 10:05:25,165 - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`teacher_first_name`) = 'akshay' WHERE (`teacher_first_name`) = 'rajat'' at line 1") 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`teacher_first_name`) = 'akshay' WHERE (`teacher_first_name`) = 'rajat'' at line 1")
2022-02-03 10:07:38,982 - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`teacher_first_name`) = 'akshay' WHERE (`teacher_first_name`) = 'rajat'' at line 1") 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`teacher_first_name`) = 'akshay' WHERE (`teacher_first_name`) = 'rajat'' at line 1")
2022-02-03 10:10:31,811 - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(teacher_first_name) = 'vish' WHERE (teacher_first_name) = 'rajat'' at line 1") 
 
Traceback (most recent call last):
  File "D:\bridgelabz\python\py_mysql\SQL\sql_operations.py", line 62, in update_query_operation
    if self.cursor_obj.execute(query, data):
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\vishwanath\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(teacher_first_name) = 'vish' WHERE (teacher_first_name) = 'rajat'' at line 1")
